title: Daniel Brown
description: Data Scientist
url: "https://danielsbrown3.github.io"
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_posts"
    values:
      layout: "post"
  - scope:
      path: "_projects"
    values:
      layout: "project"

# Plugins
plugins:
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore

# Navigation
navigation:
  - title: Home
    url: /
  - title: Writing
    url: /writing
  - title: Projects
    url: /projects
  - title: About
    url: /about

# Theme settings
theme:
  accent_color: "#4299e1"
  dark_mode: true 